### ISSUE TITLE
Downloading on istex with sid=termsuite

### ISSUE THREAD

**Issue by kerphi** [termsuite/termsuite-istex#1]
Please could you add the sid=termsuite in the querystring when searching and downloading ISTEX documents ? It will help us (istex platform team) to know how is used ISTEX.

Thanks in advance.

**Comment by dcram** [comment]
Appended `sid=termsuite` to all requests, or `sid=termsuite-test` when requests are initiated from termsuite-istex's functional tests.

**Comment by kerphi** [comment]
Great, thank you for the quick patch :+1:
